import sounddevice as sd
import soundfile as sf
from kokoro_onnx import Kokoro

class KokoroTTS(Kokoro):
    def __init__(self, voice: str = "af_sarah"):
        super().__init__("kokoro-v0_19.onnx", "voices.json")

    def generate(self, voice: str, msg: str):
        return self.create(
            msg, voice=voice,
            speed=1.0, lang="en-us"
        )

    def play(self, voice: str, msg: str):
        data = self.generate(voice, msg)

        print("Playing audio...")
        sd.play(*data)
        sd.wait()

    def save(self, voice: str, msg: str, fname: str):
        data = self.generate(voice, msg)

        print(f"Saving to {fname}")
        sf.write(f"{fname}", *data)

def main():
    kokoro = KokoroTTS("am_adam") # or am_michael
    # kokoro.play("Hi! This audio was generated by ko-ko-ro, the revolutionary Text-to-Speech model.")
    kokoro.play("Is this a question? ... Or is this? ... ... I'm unsure.") #, "test.wav")

if __name__ == "__main__":
    main()
